config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
]

core/erp/urls.py
from django.urls import path
from core.erp.views.category.views import *

app_name = 'erp'

urlpatterns = [
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/edit/<int:pk>/', CategoryUpdateView.as_view(), name='category_edit'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
]

templates/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>a Industrial Development</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{entity}}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Javascript block -->
    {% block javascript %}

    {% endblock %}
    </body>
{% endblock %}

templates/delete.html
{% extends 'body.html' %}
{% block content %}
<form action="." method="POST">
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-trash"></i> &nbsp;
                {{title}}
            </h3>
        </div>

        <div class="card-body">
            {% csrf_token %}
            <div class="alert alert-danger alert-dismissible">
                <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
                ¿Estas seguro  de eliminar el registro nro {{ object.id }} ?
                </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-danger btn-flat">
                <i class="fas fa-save"></i>  Si, aceptar
            </button>
            <a href="{{ list_url }}" class="btn btn-info btn-flat">
                <i class="fas fa-times"></i>  No, cancelar
            </a>
        </div>

    </div>
</form>

<script>

    $('form').on('submit', function(e) {
        e.preventDefault();
        var parameters = $(this).serializeArray();
        $.ajax({
                url :  window.location.pathname,
                type: 'POST',
                data : parameters,
                dataType: 'json',

            }).done(function(data) {
               if(!data.hasOwnProperty('error')){
                    location.href = '{{ list_url }}';
                    return false
               }
               message_error(data.error);
            }).fail(function(jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function(data) {

            });
    });

</script>

{% endblock %}

templates/footer.html
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        Ing. DVC
    </div>
    <!-- Default to the left -->
    <strong>CopyRight &copy;2022<a href="#"> Industrial Development</a>.</strong> Derechos Reservados
</footer>

templates/form.html
{% extends 'body.html' %}
{% load widget_tweaks %}
{% block content %}
<form action="" method="POST">
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                {% if action == 'add' %}
                <i class="fas fa-plus"></i> &nbsp;
                {% else %}
                <i class="fas fa-edit"></i> &nbsp;
                {% endif %}
                {{title}}
            </h3>
        </div>

        <div class="card-body">
            {% csrf_token %}
            <input type="hidden" name="action" value="{{ action }}">
            {% if form.errors %}
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al intentar guardar el registro!</h5>
                <ul>
                {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
                {% endfor %}
            </ul>
                </div>
            {% endif %}

            {% for field in form.visible_fields %}
            <div class="form-group">
                <label for="">{{ field.label }}</label>
                {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
            </div>
            {% endfor %}
            
        </div>
        <div class="card-footer">
            <button class="btn btn-primary btn-flat btnTest">
                <i class="fas fa-save"></i>  Guardar registro
            </button>
        </div>

    </div>
</form>
<script>

    {% if form.errors %}
    var errors = ''
    {% for field in form %}
    {% for error in field.errors %}
    errors += '{{ error }} \n'
    {% endfor %}
    {% endfor %}
    Swal.fire({
        title: 'Error',
        text: errors,
        icon: 'error',
    });
    {% endif %}

    $('form').on('submit', function(e) {
        e.preventDefault();
        var parameters = $(this).serializeArray();
        $.ajax({
                url :  window.location.pathname,
                type: 'POST',
                data : parameters,
                dataType: 'json',

            }).done(function(data) {
               if(!data.hasOwnProperty('error')){
                    location.href = '{{ list_url }}';
                    return false
               }
               message_error(data.error);
            }).fail(function(jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function(data) {

            });
    });

</script>

{% endblock %}

templates/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
        <a href="#" class="navbar-brand">
            <img src="{% static 'img/logo.png' %}" alt="AdminLTE Logo"
                 class="brand-image"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">IndDev</span>
        </a>
        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="#" class="nav-link"><i class="fas fa-home"></i> Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Mantenimientos</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="#" class="dropdown-item"><i class="fas fa-truck-loading"></i> Categorías</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-boxes"></i> Productos</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-users"></i> Clientes</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-shopping-cart"></i> Ventas</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-bell"></i>
                    <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header">15 Notifications</span>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-envelope mr-2"></i> 4 new messages
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-users mr-2"></i> 8 friend requests
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-file mr-2"></i> 3 new reports
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{ title }} </title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.2.0/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.2.0/js/adminlte.min.js' %}"></script>

    <!-- Sweet Alert  -->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>

    <!-- function  -->
    <script src="{% static 'js/function.js' %}"></script>

    <!-- Head block -->
    {% block head %}

    {% endblock %}

</head>

{% block body %}

{% endblock %}
</html>

templates/index.html
{% extends 'body.html' %}

{% block content %}

{% endblock %}

templates/list.html
{% extends 'body.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}" />
<link rel="stylesheet"
    href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}" />
<script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>
{% endblock %}

{% block content %}

<div class="card card-default">
    <div class="card-header">
        <h3 class="card-title">
            <i class="fas fa-search"></i>
            {{title}}
        </h3>
    </div>

    <div class="card-body">
        <table class="table" id="data">
            <thead>
                {% block columns %}

                {% endblock %}

            </thead>
            <tbody>
                {% block rows %}

                {% endblock %}

            </tbody>
        </table>
    </div>
    <div class="card-footer">
        <a href="{{ create_url }}" class="btn btn-primary btn-flat btnTest">
            <i class="fas fa-plus"></i> Nuevo registro
        </a>
    </div>

</div>

{% endblock %}

{% block javascript %}

<script>
    $(function() {
        $('#data').DataTable({
            responsive: true,
            autoWidth: false
        });

        $('.btnTest').on('click', function () {
            $.ajax({
                url :  "{% url 'erp:category_list' %}",
                type: 'POST',
                data : {id:1},
                dataType: 'json',

            }).done(function(data) {
                console.log(data);
            }).fail(function(data) {
                alert('error')
            }).always(function(data) {

            });
        });
    });
    
</script>

{% endblock %}